# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'quiq', path: '..'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end
